# @package _global_
model:
  name: convnext

  architecture:
    backbone: convnext_small
    pretrained: true
    freeze_backbone: true
    global_pool: avg
    chunk_size: 64
    grad_checkpoint: false
    
  classifier:
    dropout: 0.3
    num_classes: 2