# @package _global_
model:
  name: convnext_kd
  classifier:
    dropout: 0.3
    num_classes: 2

kd:
  teacher:
    model: video_swin
    checkpoint: checkpoints/video_swin/best.pth

  student:
    model: convnext
    checkpoint: null