# @package _global_
model:
  name: timesformer

  architecture:
    pretrained_model: facebook/timesformer-base-finetuned-k400
    pretrained: true
    freeze_backbone: true
    num_frames: 15               
    image_size: 224            

  classifier:
    dropout: 0.3
    num_classes: 2